### ISSUE TITLE
No joy testing BERT 2.1.0

### ISSUE THREAD

**Issue by PGS62** [sdllc/Basic-Excel-R-Toolkit#101]
Dear Duncan

Great to see that BERT 2.0.1 will support Julia as well as R... But, unfortunately I've not been able to get BERT 2.0.1 working on any of the three PCs on which I've tried to install it, all three of which previously had BERT 1.63 working correctly. The PCs had:
1) Windows 7, Office 2016 32 bit
2) Windows 7, Office 2013 32 bit
3) Windows 10, Office 2016 64 bit

On the 3rd PC, Under:
File > Options > Add-ins > COM Ass-ins > Go > BERT2 Ribbon Menu

I see:
Load Behavior: Not loaded. A runtime error occurred during the loading of the COM Add-in.

Also a call from VBA to Application.RegisteredFunctions returns Null, which I guess is not as it should be.

Not sure if I can tell you anything more helpful

Best wishes

Philip

**Comment by PGS62** [comment]
Oops, for Ass-in read Add-in

**Comment by duncanwerner** [comment]
Best error ever (you can edit). 

Sorry about that; if you re-enable BERT1 it should work, we'll investigate.  Regarding the windows 7 machines, are those (the OS) 32- or 64-bit?

**Comment by PGS62** [comment]
Yes, switching back to BERT 1 was no problem.

The Windows 7 was 64 bit.

**Comment by StatsMan53** [comment]
FYI I have had no problems using 2.1.0 with either 32-bit or 64-bit Windows 7 Professional with Office 365.

**Comment by StatsMan53** [comment]
Scratch that.  Apparently the "(2017-11-30)" on the download page applies only to R.  I am still running 1.6.4, but will test the upgrade latter today on a computer that I can afford to have problems with.

**Comment by StatsMan53** [comment]
Or not ... the download link is broken

**Comment by kerry-ja** [comment]
I have the same situation; 
On the 3rd PC, Under:
File > Options > Add-ins > COM Add-ins > Go > BERT2 Ribbon Menu

I see:
Load Behavior: Not loaded. A runtime error occurred during the loading of the COM Add-in.

Windows 7 Pro 64 Bit OS running Microsoft Excel 2016 64 bit.

**Comment by PGS62** [comment]
Better news. I just tried installing BERT 2.2.1 on one of the same PCs that failed with 2.1.0 and all looks to be working correctly.
Thanks for fixing!
