### ISSUE TITLE
BERT v2.2.1: AddUserButton does not work (as it did in v1)

### ISSUE THREAD

**Issue by stephansgit** [sdllc/Basic-Excel-R-Toolkit#111]
I migrated to BERT v2.2.1 (from BERT v1.6 or so).
I have a couple of User Button-functions, which sit in R-scripts within my ```BERT2/functions/``` folder (I copied them over). 

__Problem__:
The User Buttons do not display in the ribbon.

Starting Excel and BERT gives the following error in the Shell:
```
Loading script file: C:\Users\...\Documents\BERT2\functions\where_the_buttons_sit.R
Error in eval(ei, envir) : attempt to apply non-function
```

__Reproduce__:
Equally, following the example provided [here](https://bert-toolkit.com/user-buttons.html) does not work and gives the same error:

```
BERT$AddUserButton( "Histogram", function(){
  Selection <- as.numeric( Get.Selection());
  if( length( Selection ) > 2 ){
  hist( Selection );
  }
  });
```
gives
```
Error: attempt to apply non-function
```

Are User Buttons still supported in BERT v2? I'm asking because also the [documentation on User Buttons](https://bert-toolkit.com/user-buttons.html) does not seem to be easily accessible with the current website (or maybe I just didn't look good enough)

Thanks for any hint (and the great product)!

---------
System:
Windows 7, 6.1.7601, Excel O365

**Comment by duncanwerner** [comment]
We did drop user buttons in v2. We didn't think anyone was using them.

We could bring them back, I don't think it would be too much trouble, but the API might need to change a little bit owing to the new structure.

**Comment by stephansgit** [comment]
I do like them and we do use them. They are handy for some standard plots, when you don't want to clutter your spreadsheet.

Let's see what others say.

**Comment by leo-liar** [comment]
I agree with **stephansgit** and would very much like to have user buttons back if possible.

**Comment by duncanwerner** [comment]
OK, we'll make that happen. As I said the API will have to change a little bit, but it should be possible to translate without too much effort.

**Comment by duncanwerner** [comment]
I added user buttons back in a83008cd1f507cc3f64702fcfc1b58b649c70af9. There's a pre-release build 2.3.4 if you want to try it. The API is functionally the same, so it should work without modification, but when we add support for Julia the behavior will change a little bit -- clearing buttons will clear for one language only, and buttons will be inserted in language order.

**Comment by stephansgit** [comment]
Thanks @duncanwerner for putting it back in!

I tested (in version 2.3.6) and it seems to work with minor changes to my original code (below for the benefit of other users maybe):
 
**Base graphics:**
(this works)
```
BERT$AddUserButton( "Histogram", function(){
	Selection <- as.numeric(EXCEL$Application$get_Selection$get_Value());
	if( length( Selection ) > 2 ){
      hist( Selection );
	}
});
```

**ggplot2**:
Following [this example](https://bert-toolkit.com/user-buttons.html) on using _ggplot2_ (section Finished Example) I can only make it work if I add a `print(p)` statement (which clearly is no problem)
```
BERT$AddUserButton( "Histogram_fancy", function(){
	s <- EXCEL$Application$get_Selection();
	m <- as.numeric( s$get_Value());
	cap <- sprintf("N=%d, mu=%3.2f, s=%3.2f", length(m), mean(m), sd(m));
	if( length( m ) > 2 ){
		a <- s$get_Address();
		p <- qplot( m, geom="histogram", fill=I("blue"), alpha=I(.2), col=I("blue"),
          binwidth=diff(range(m))/13, xlab=a, main=cap );
	}
  print(p)
}, "Chart3DColumnChart");
```
Thanks again!


-------------

BERT v2.3.6
Windows 7, 6.1.7601, Excel O365
