### ISSUE TITLE
Cannot insert special characters/symbols into shell

### ISSUE THREAD

**Issue by leo-liar** [sdllc/Basic-Excel-R-Toolkit#112]
Using the most recent BERT v2.3.3 I'm not able to enter any character requiring `CTRL`+`ALT` for input into the R or Julia shell. For me using a German keyboard layout this means I can't enter, amongst others, curly `{}` and square `[]` brackets or backslashes `\`.

Haven't yet tested if this is an issue in older versions, too.
The editor doesn't have this problem and handles every input just fine.

System:
Windows 8.1 Pro x64
Excel 2016 (MSO 365) (v16.0.9126.2116)

EDIT: Just tried copy-pasting some special characters into the shell which worked. (Although paste hotkey `CTRL`+`SHIFT`+`INS` didn't work, had to use Windows key combo `SHIFT`+`INS`.)

**Comment by duncanwerner** [comment]
This is fixed in 1b8d31f3314ed49d1f22e4515c307f050fe00b33. There's a pre-release build 2.3.4 if you want to try it.

**Comment by leo-liar** [comment]
Yes, the issue is fixed in 2.3.4.

Thanks!
