### ISSUE TITLE
How to get value as text string 

### ISSUE THREAD

**Issue by u2aziz** [sdllc/Basic-Excel-R-Toolkit#123]
Hi,

How to get range value as a string 
ns <- EXCEL$Application$get_Sheets("ns")$get_Range( "A1:N23141" )$get_Value()
Sometimes my values are factor, sometimes numeric 

Aziz 
PS. This software is beautiful

**Comment by duncanwerner** [comment]
If you are not using the latest version, this might be a function of #120 where we were setting the wrong NA type. Also for the `range.to.data.frame` function, after #121 we added the stringsAsFactors parameter, so set that to false and you should be able to force strings.

**Comment by u2aziz** [comment]
thanks for support Duncan
approciated
