### ISSUE TITLE
Large matrices with header row

### ISSUE THREAD

**Issue by mat-x** [sdllc/Basic-Excel-R-Toolkit#131]
I've been struggling with a persistent crash and I've managed to reproduce it reliably on my machine. If I pass a large matrix to an R function *that has a header row*, then BERT will crash with the error "ControlR.exe has stopped working".

I've attached a spreadsheet that will do this fairly reliably for me. To see the problem:

First add the following to your BERT functions:
Dummy <- function(...){
  1
}

Then open the spreadsheet ([BERT_CrashTest 4.xlsx](https://github.com/sdllc/Basic-Excel-R-Toolkit/files/2075853/BERT_CrashTest.4.xlsx)), and refresh the function in cell A1 a couple of times. This will work with no issues.

Now change the input to the function from B3 to B2 (i.e. including the header row). This will crash every time for me. (if that doesn't work for you, try more rows - I'm not sure if the exact cutoff will vary)

Workaround for now is to input the column headers and content as separate parameters. However, we do have some mixed categorical data (i.e. numbers and strings in the same column) that it would be nice to be able use without crashing.

I'm using: Excel 2010 version 14.0.7208.5000 (32-bit)
BERT version 2.3.9

Cheers,
Matt

**Comment by duncanwerner** [comment]
Pretty sure this is caused by not protecting the list as it was generated, which was fixed in 08050cac09c8a704e19c4692adc720667ae5f3fa. I'll get a release built with this patch shortly.

**Comment by duncanwerner** [comment]
Try this update and let me know what happens:
https://github.com/sdllc/Basic-Excel-R-Toolkit/releases/tag/2.3.10

**Comment by mat-x** [comment]
Yes, I've just installed 2.3.10 and it now works perfectly.

Thanks very much for such a speedy and accurate response :-)
