### ISSUE TITLE
BERT 2.4.1 doesn't load Julia

### ISSUE THREAD

**Issue by leo-liar** [sdllc/Basic-Excel-R-Toolkit#132]
<details><summary>System(s)</summary>

home | work
:---: | :---:
Windows 8.1 Pro x64 | Windows 10 Enterprise x64
Excel 2016 (MSO 365) v16.0.9126.2116 | Excel 2010 (MSO Standard 2010) v14.0.7208.5000

</details>

---

The most recent release [**v2.4.1**][1] doesn't load the Julia console anymore on both above mentioned systems.

[1]: https://github.com/sdllc/Basic-Excel-R-Toolkit/releases/2.4.1 "Update for R 3.5.0"

**Comment by duncanwerner** [comment]
Generally speaking anything marked as "pre-release" should be considered unstable. That said, I there weren't any changes related to Julia in that release (or the previous one).

What version of Julia are you using?

**Comment by leo-liar** [comment]
I know that this version is not to be considered stable and it's not causing me any trouble right now, I just wanted to let you know of said error.

I'm using [**Julia v0.6.2 x64**][1] on both machines. On my home computer it's a standard installation, no changes during setup and BERT recognized it without further configuration. On my work machine I changed folders but configured BERT accordingly.

I upgraded from [**v2.3.9**][2] (**home**) and [**v2.3.10**][3] (**work**) and in both cases Julia worked before. In **v2.4.1** _ControlJulia.exe_ is terminated immediately after starting Excel.

I just saw that there's a new Julia release ([**v0.6.3**][4]). I can give this one a try, maybe it solves this problem.

Do you need any further information?

[1]: https://julialang-s3.julialang.org/bin/winnt/x64/0.6/julia-0.6.2-win64.exe "Current Release (v0.6.2)"
[2]: https://github.com/sdllc/Basic-Excel-R-Toolkit/releases/2.3.9 "Bugfixes"
[3]: https://github.com/sdllc/Basic-Excel-R-Toolkit/releases/2.3.10 "Updates and Fixes"
[4]: https://julialang-s3.julialang.org/bin/winnt/x64/0.6/julia-0.6.3-win64.exe "Current Release (v0.6.3)"

**Comment by duncanwerner** [comment]
Thanks, I was wondering if you were using Julia v0.7. I don't think 0.6.3 vs 0.6.2 will make a difference. I'll see if I can figure out what's wrong. 

If the control process is exiting immediately, that means either (1) it can't find the required DLLs, or (2) there's a version mismatch. But if nothing changed, it should just work as before.

**Comment by duncanwerner** [comment]
Looks like I left some debug symbols in there. Please try the new one (2.4.2) if you have a chance.

**Comment by leo-liar** [comment]
Yes, with 2.4.2 the Julia console is back.

Thank you!
