### ISSUE TITLE
NaNs in R datatable become large number in excel

### ISSUE THREAD

**Issue by glitests** [sdllc/Basic-Excel-R-Toolkit#14]
Thanks for your suggestion on the previous issue.
Here's another problem. I am returning the following data table to Excel.

```
Classes 'data.table' and 'data.frame':	548 obs. of  3 variables:
 $ Date            : Date, format: "2015-02-01" "2015-02-02" ...
 $ V1: num  107 106 NaN NaN 107 ...
 $ V2: num  103 103 NaN NaN 103 ...
 - attr(*, ".internal.selfref")=<externalptr> 

```
The NaNs become 
![image](https://cloud.githubusercontent.com/assets/18304035/14738748/e4ee3826-08b5-11e6-8a69-304ae0c86cb7.png)

Please advise. These NaN or NA should not show any numeric value.

**Comment by duncanwerner** [comment]
Should be resolved in release v0.70 (along with other type translation issues).
