### ISSUE TITLE
Forecast functions

### ISSUE THREAD

**Issue by Despinat1** [sdllc/Basic-Excel-R-Toolkit#15]
Hi Duncan,
I have tried using Foo <- function( rng ){
  process(rng);
}
to import forecast R functions into Excel (from the forecast package).  The functions appear in Excel but when I try to use I get #Value!.  Excel seems to read the code correctly, there are no errors when reading the start-up file, I am not sure what I am missing.  I am particularly interested in the forecast.ets function.

Thank you,
Despina

**Comment by duncanwerner** [comment]
What is the `process` function?

**Comment by Despinat1** [comment]
Hi,
Thank you for your quick response.  I have attached the function in a word
file. It is taken from R software, from the forecast package, I've
extracted it using edit(forecast.ets).
Again many thanks,
Despina

**Comment by duncanwerner** [comment]
Closing stale threads / non-issues.  If this is an issue and is not resolved, please re-open.
