### ISSUE TITLE
R environment interference

### ISSUE THREAD

**Issue by freiwerk** [sdllc/Basic-Excel-R-Toolkit#18]
Hi there,

we are just checking out if BERT is suited to replace our old interface between R and Excel. We really love the idea of this plugin!

However we came along a small issue where BERT interferes with the local environment. Obviously we have a local R installation for our tasks and we do call the local R scripts form VBA by using `shell()` or `CreateObject("WScript.Shell")`.

If we do call the local R installation from VBA via shell, BERT somehow interferres with the environment, so our local R installation looses the library path to the userdocs-folder (in Windows, R creates a local plugin library in the user's documents folder). If BERT is deactivated or we call the R script from a command line not opened by VBA, everything works fine however. So there is some interference with the environment.

Just wanted to let you know about this, as I think that dual installation and local execution of R via VBA will be an established task for users interested in BERT - If you have any hints how to avoid this issue, please let me know.

Best
freiwerk

**Comment by duncanwerner** [comment]
This is probably happening because of environment variables.  Before we start R in the Excel process, we set two variables: R_HOME and R_USER.  If you open a shell after that, it will have the updated values for these variables.

If you open a shell from VBA, you could explicitly set your environment variables back to the original values in the shell.  That would solve your path resolution issues.   

However it might make more sense to just use a single instance of R, unless there's some reason not to.  At the moment you can do that by setting the configuration values in BERT to your existing R installation (home and user).   

Or, depending on what you need, you might just set one or the other.  I'll have to experiment a bit to see what the impact of that would be.

**Comment by freiwerk** [comment]
Hi Duncan,

thanks for the response. We do work on a solution to reset the env-variable in the shell.

In general, however, we do not understand the concept of the environment in detail yet - what would happen if we change home and user to our R installation? Wouldn't this mean that BERT uses our local R? (didn't you mention on your page that this might be quite instable, espeacially if version number differs from the R package in BERT?) Or could we simply change the user path?

**Comment by freiwerk** [comment]
Ok, just found out that this it does not work to redirect my bert USER profile to the local installation. However, you were right it's the R_USER varaible that causes the interference. It's interesting to me that a shell opened in VBA automatically defines R_USER, even i just open cmd.exe and start R later on...

**Comment by duncanwerner** [comment]
> a shell opened in VBA automatically defines R_USER

By default, environment variables inherit from their parent process.  So when we set R_USER in the Excel process, any subsequent processes that are created by Excel will have the same value set.  You can change it in the child process, though.

> this might be quite instable, espeacially if version number differs from the R package in BERT

This is probably OK for major versions of R (meaning 3.1, 3.2 and 3.3 would be OK), but for now, we require that the version of R used by BERT is the same version as when it's built, which is currently 3.3.0.  We can relax this requirement and just require the major version, but for now, if the versions are different, BERT will complain.

Like I said I still need to explore some things with the environment to see what's a good solution.

By the way if the only thing that you need is the path to your user library directory, you can set that explicitly using `.libPaths()`.

**Comment by freiwerk** [comment]
Ah, I didn't know that processes have own environment variables and that they are inherited. Knowing that, I can simply use a `set` command to rewrite the variables... That's the solution that works best for me, thanks!

**Comment by duncanwerner** [comment]
Closing stale threads / non-issues.  If this is an issue and is not resolved, please re-open.
