### ISSUE TITLE
Can I writing R-code in the spreadsheet and export it to the Bert-console?

### ISSUE THREAD

**Issue by alexlangnau** [sdllc/Basic-Excel-R-Toolkit#19]
Sorry, in case this is not the right forum for my question !

I am wondering whether it is possible to write simple R-code in the spreadsheet - say something along the line of:

![bert2](https://cloud.githubusercontent.com/assets/20053612/16361387/7d33449e-3b8f-11e6-9a01-33bb80adb898.JPG)

and then export it to Bert-console?

This type of procedure is, for example, quite commonly used by traders in investment banks when one needs to quickly get indicative pricing of a new product without having to wait for a new release of the official pricing library.

**Comment by alexlangnau** [comment]
Hallo,

guess I can answer my own question:

(i) define the following R function
     myGeneric<- function(str) 
     {
       eval(parse(text = str))
     }
  in the Bert console and reload.

(ii) set spreadsheet cell A1 to

      source("C:/test.R")

(iii) call R.myGeneric with argument being the content of cell A1

**Comment by duncanwerner** [comment]
I think you are making this too complicated.  (Also, issues should generally be for bugs or feature requests).  Why not just run that code within the console?  You don't need to go back-and-forth to the spreadsheet.

**Comment by duncanwerner** [comment]
Closing stale threads / non-issues.  If this is an issue and is not resolved, please re-open.
