### ISSUE TITLE
Stability issues - problem with "bertribbon.connect"

### ISSUE THREAD

**Issue by freiwerk** [sdllc/Basic-Excel-R-Toolkit#20]
Hi there,

we du have some stability issues with BERT, it sometimes causes a problem at startup of Excel (addin: bertribbon.connect). Is there any log-file we can analyze?

Also, as the name indicates, only the ribbon is affected. Could we avoid such ribbon issues by simply loading BERTMGRXX.xll? Am I right that the COM addin is not needed?

**Comment by duncanwerner** [comment]
Regarding stability, you can check the event logs at the time of the crash (not at Excel startup), but any messages will probably just indicate that there was a crash.  If you find anything interesting, please let me know.  When Excel crashes it sets a flag in the registry, and the next time you start you get that message.

The unstable part is probably console functions talking to Excel (via the API or COM).  The COM component contains the ribbon and the console.  You can do without the COM add-in if you use the BERTMGR add-in.  For various reasons, it's not possible to load BERT directly into Excel.  We need to load some other add-in first, and then that one loads BERT.  

Originally this was what the BERTMGR add-in was for, but it got replaced by the COM add-in / ribbon menu.  You should be able to use BERTMGR and drop the COM add-in.

**Comment by freiwerk** [comment]
Thanks. I'll try to use BERTMGR to test if stability improves. However, the .xll file doesn't load a interface in the "addin"-ribbon (i think i rember that the .xll previously loaded buttons). Is there a way I can open the console manually / to replace the buttons via a .customUI?

**Comment by duncanwerner** [comment]
Closing stale threads / non-issues.  If this is an issue and is not resolved, please re-open.
