### ISSUE TITLE
Error in file(file, "rt") : cannot open the connection in  BERT CONSOLE

### ISSUE THREAD

**Issue by basakbb** [sdllc/Basic-Excel-R-Toolkit#21]
Is there any problem in Bert Console about reading the data?
My function involves a data so I have to read this data.

The home directory of the BERT console is C:\Users\SONY PC\AppData\Roaming\BERT
Although there is a text file which name is "bloodpressure.txt" in the same place. BERT can not read the tex file . It gives the warning message: Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") : cannot open file 'bloodpressure.txt': No such file or directory
What is the problem of not reading tex file although this tex file exists?

**Comment by basakbb** [comment]
In addition, when I try to read the data as
read.table("C:\Users\SONY PC\AppData\Roaming\BERT\bloodpressure.txt")
it gives a different warning:
 (an error occurred processing the command.  is excel busy?)
Error: '\U' used without hex digits in character string starting ""C:\U"

**Comment by duncanwerner** [comment]
Closing stale threads / non-issues.  If this is an issue and is not resolved, please re-open.
