### ISSUE TITLE
Enable the BERT Ribbon Menu Excel crashes

### ISSUE THREAD

**Issue by bjkuijpers** [sdllc/Basic-Excel-R-Toolkit#28]
I'm on excel 2016 32-bit and for some reason when I try to Enable the BERT Ribbon Menu Excel crashes. (BERTRibbon2x86.dll)

Have tried fresh install for excel and re-installing Bert.

<img width="503" alt="c1" src="https://cloud.githubusercontent.com/assets/9797836/22467596/9283f9a0-e7c5-11e6-9b25-a1ae8673ebff.PNG">
<img width="266" alt="c2" src="https://cloud.githubusercontent.com/assets/9797836/22467597/928bc040-e7c5-11e6-9286-ee54dd2b35ce.PNG">

**Comment by duncanwerner** [comment]
Hi,

What version of Excel and Windows are you using?  (I ask so I can set up a VM as close as possible).  Also, when you ran the installer, was the ribbon menu not automatically enabled?

**Comment by bjkuijpers** [comment]
Windows: Windows 10 Pro Version 1607
Office: Microsoft Office Home and Business 2016 Version 1612 (Build 7668.2066)

The ribbon was automatically enabled but after couple of crashes it no longer was.

**Comment by duncanwerner** [comment]
There's no good reason for the ribbon to crash on load, except that this is where it loads the rest of BERT (via the .xll add-in).  If it can't find the xll it should fail gracefully (or at least silently).  It also loads the xml for the ribbon, but as far as I can tell there's no way for this to crash it either (famous last words, perhaps).

Given that, the most likely reason it's crashing has something to do with loading the XLL: either starting up R or running the initial R code.  

There are a couple of ways to trace this back, but here is what I would suggest first: try removing the XLL and then try it again.  Close Excel, then go to the BERT directory in %APPDATA% (if you're not familiar, use the path in your screen cap above).  Rename the file BERT32.xll to something else and try again.  If that's correct, then the ribbon should load OK (but not do anything).  The next step would be to figure out if it's a problem loading R or a problem with the startup code.

**Comment by bjkuijpers** [comment]
OK renamed BERT32.xll and the ribbon does who up. How do I check if it's startup code?

**Comment by duncanwerner** [comment]
Assuming you're on the current version of BERT, startup code will be in the documents folder.  If you are on an earlier version, or if you've upgraded, you might have the old functions file.

Rename the BERT xll so it's back to normal (should be BERT32.xll).  If you have a `functions.R` file in the same directory, remove (rename) that.

The BERT functions directory is in your Documents folder, under BERT/functions.  When it starts up, BERT will read everything in this directory.  Try taking everything out of there (move them somewhere else temporarily) and try starting up again.

**Comment by bjkuijpers** [comment]
Bert is functioning but I still have to manually add the addin each time on an excel startin?

**Comment by duncanwerner** [comment]
At some point Excel changed the "load behavior".  In your picture above it's listed as "unloaded".  This should be "load at startup".  There is no way in Excel to change this setting.  A reinstall of BERT should straighten it out (make sure Excel isn't running).  If you're familiar with the registry, this field is set here:

`HKCU\SOFTWARE\Microsoft\Office\Excel\Addins\BERTRibbon.Connect`

the value of `LoadBehavior` should be `3` (Load on startup).  [See here for more](https://msdn.microsoft.com/en-us/library/bb386106.aspx#LoadBehavior) -- this has nothing to do with VSTO, but it's the same value.

**Comment by bjkuijpers** [comment]
Everything up and running, much appreciated.
