### ISSUE TITLE
kmeans.xlsb Runtime error 1004

### ISSUE THREAD

**Issue by tranzmatt** [sdllc/Basic-Excel-R-Toolkit#30]
I'm trying to run the kmeans.xlsb example and Excel 2016 is throwing up an Runtime 1004 error on the following line:

`Set rng = sel.Offset(1, 0).Resize(sel.Rows.Count - 1, 1)`

It doesn't look right, but I'm not sure how to fix it.

**Comment by duncanwerner** [comment]
You probably didn't select the table before pressing the button.  It's selected by default, but if you get Excel security warnings they remove the selection.

**Comment by tranzmatt** [comment]
I'll give it a shot as soon as I figure out why I can't run BERT :(

**Comment by tranzmatt** [comment]
Yes, you're correct.  My bad for missing the obvious instruction.  I feel kinda dumb. ^_^;;

**Comment by duncanwerner** [comment]
I didn't want to mention it.  Current version of the file has a popup if you do that.
