### ISSUE TITLE
Prblem with R1C1 style

### ISSUE THREAD

**Issue by nksingh62** [sdllc/Basic-Excel-R-Toolkit#33]
For BERT 1.24, problem occurs with R1C1 style while it is working nicely for A1 style. 

`new.sheet<-wb$get_Sheets()$Add()
range<-new.sheet$get_Range("A1:J62")
range<-new.sheet$get_Range("R1C1:R62C10")

_**Error in new.sheet$get_Range("R1C1:R62C10") : 
  COM Exception in Invoke (Range) 0x80020009: Exception occurred.**_
 `

**Comment by duncanwerner** [comment]
That's because the Excel Range object does not support R1C1.  See

https://msdn.microsoft.com/en-us/library/office/ff836512.aspx
