### ISSUE TITLE
Problem in BERT 1.33 Installation without administrator privilege 

### ISSUE THREAD

**Issue by nksingh62** [sdllc/Basic-Excel-R-Toolkit#37]
Without administrator privilege on Windows 2007, message “**unable to write in C:\config.msi. Log on as administrator**” is flashed. With administrator privilege, BERT is installed properly.

**Comment by duncanwerner** [comment]
You do not need administrator privileges to install, and we do not recommend running as Administrator.  I'm not sure why your configuration required writing to that file, but I think that's something specific to your configuration.
