### ISSUE TITLE
HowTo: drop the 1st column of row names returned?

### ISSUE THREAD

**Issue by malcook** [sdllc/Basic-Excel-R-Toolkit#59]
Is there a way to avoid having row names returns from every call to BERT.Call and/or in calling R functions using BERT.

**Comment by duncanwerner** [comment]
For data.frames (and data.tables) we always return row names and column names.  You can convert your data to a different form if you don't want the row names. The rationale is that historically people (sometimes) put relevant information in row names.  At this point it's just not worth changing it.  

We can test for row names, but data.frames _always_ have row names, even if you explicitly remove them; a frame will just set row names to (1, 2, 3...).

**Comment by malcook** [comment]
Thanks for the answer.  Appreciated!
