### ISSUE TITLE
Bert Addin disabled in Excel 

### ISSUE THREAD

**Issue by SmartSupport** [sdllc/Basic-Excel-R-Toolkit#60]
Bert Addin suddenly became disabled in Excel 2016 and when we try to enable it excel does not open and displays a message that the Bert Addin needs to be disabled for excel to be able to start.

We tried uninstalling Bert and and re installing it but still the same issue happens. Please advice further.

**Comment by duncanwerner** [comment]
See #52, #53, #46

**Comment by SmartSupport** [comment]
Hi Support, 

We have tried all these solutions already and made sure its installed as it should be but still its causing issues and even if we enable it, Excel refuses to launch until the add in is disabled again.
