### ISSUE TITLE
Problems Quadprog package

### ISSUE THREAD

**Issue by MarcoGHub** [sdllc/Basic-Excel-R-Toolkit#61]
If I run the following code:

library(quadprog)
solve.my.QP <- function(A, p, C) {
  solve.QP(Dmat=2*p*C,
           dvec=A,
           Amat=cbind(diag(1, length(A)), rep(1, length(A)), rep(-1, length(A))),
           bvec=c(rep(0, length(A)), 1, -1))$solution
}

solve.my.QP(c(0, 0), 1, diag(1, 2))

I get the following error message:
Error in solve.QP(Dmat = 2 * p * C, dvec = A, Amat = cbind(diag(1, length(A)),  : 
  object '.QP_qpgen2' not found

**Comment by duncanwerner** [comment]
(1) That works for me, so it's not a BERT issue:
```r
> solve.my.QP(c(0, 0), 1, diag(1, 2))
[1] 0.5 0.5
```
(2) When using markdown, put code in three backticks so it gets formatted (and doesn't get escaped):
```r
library(quadprog)
solve.my.QP <- function(A, p, C) {
solve.QP(Dmat=2*p*C,
dvec=A,
Amat=cbind(diag(1, length(A)), rep(1, length(A)), rep(-1, length(A))),
bvec=c(rep(0, length(A)), 1, -1))$solution
}

solve.my.QP(c(0, 0), 1, diag(1, 2))
```
