### ISSUE TITLE
Can't Get OnTime to work

### ISSUE THREAD

**Issue by wscheel** [sdllc/Basic-Excel-R-Toolkit#66]
Can you please tell me what I'm doing wrong with OnTime:

app=EXCEL$Application
app$OnTime(Sys.time(),"RalphWasHere",Sys.time()+10,TRUE) #sub doesn't fire
app$Run("RalphWasHere") #works fine and runs the VBA subroutine

But, this VBA code works:

Private Sub t()
  Dim dtB As Date, dtE As Date
  dtB = Now()
  dtE = DateAdd("s", 10, dtB)
  Application.OnTime dtB, "RalphWasHere", dtE, True
End Sub

Thanks,
Bill

**Comment by duncanwerner** [comment]
You're not doing anything wrong, but we don't support events (source interfaces) at the moment.  Sorry about that.  If you need to do this then the best solution is to leave the event in VBA and have VBA call some R function.

This is not on our roadmap, so if you have a good reason to use it please let us know.

**Comment by wscheel** [comment]
Thanks.  I can do what is needed with EXCEL$Application$Run.  EXCEL$Application$OnTime would be a convenience  because the R code BERT is handling is done in a separate invisible Excel "server" process.  That is so the Excel "client" process can run async.  There is handshaking going on between the processes the depends on Application.OnTime, to keep everything async,  So, Application.OnTime is an operational necessity.  But, EXCEL$Application$OnTime isn't.

There is an overhead with the client process setting up the excel server process and associated process cross-talk, but it is relatively light weight.  As another post noted, it would be great if BERT could be called directly from a VBA sub instead of a cell function that depends on a range.Calculate or application.Calculate and a synchronous hang-out.

Or, can a VBA sub call BERT and I just don't know how!

Thanks for your help.

**Comment by duncanwerner** [comment]
You can call R functions from VBA, have a look at 

https://bert-toolkit.com/r-and-vba

**Comment by wscheel** [comment]
Oh.  Nice!  Thanks
