### ISSUE TITLE
Copying and pasteing data from excel to R and back using vba

### ISSUE THREAD

**Issue by FelipeCarrillo** [sdllc/Basic-Excel-R-Toolkit#7]
Hello;
I am following the vba two examples and so far what I have tried its not working. I am trying to copy a range of cell with values to R, perform some statistics in R and get the results back to the same spreadsheet. Is it possible to do it? if so, could you provide a minimal example or direct me to a place in the wiki where I can read about it? Thanks

**Comment by duncanwerner** [comment]
What you describe in your email doesn't need to use VBA at all, and if you are using VBA I think you're just making it more complicated.  You can do this either (1) as an Excel function, or (2) using the BERT console.

As an excel function: write a function in your startup file like 

```
Foo <- function( rng ){
  process(rng);
}
```

where `process` is your R code.  Then in cell F1, put `=R.Foo( A1:C10 )`.

**Comment by duncanwerner** [comment]
To do it in the console, something like

```
> dat1 <- Get.Range( "A1:C10" )
> final_dat <- process( dat1 )
> Set.Range( "F10", final_dat )
```

It shouldn't be any more complicated than that.

**Comment by duncanwerner** [comment]
Doing it as an Excel function is probably preferred, because then you can just change values and it will recalculate.  However if it's really long, you might want to run it from the console.

**Comment by FelipeCarrillo** [comment]
I am reading the documentation and going through some of the examples right now. If my pre-saved R script is called for example 'RunExcel.R' do I simply do RunExcel('myexcelrange'); ?

**Comment by FelipeCarrillo** [comment]
I also want to run this somewhat automated with a macro.
Foo <- function( rng ){
  process(rng);
}
Can I run =R.Foo( A1:C10 ) . with vba?

**Comment by duncanwerner** [comment]
Closing stale threads / non-issues.  If this is an issue and is not resolved, please re-open.
