### ISSUE TITLE
Array truncation and padding. Please consider changing this.

### ISSUE THREAD

**Issue by PGS62** [sdllc/Basic-Excel-R-Toolkit#74]
Dear BERT developers at RiskAmp,

Your website invites comments on BERT so here’s mine…

First, I really like BERT. In my testing so far it’s worked perfectly, the interface is simple and intuitive and the documentation is well-written and even contains the odd joke, which was nice.

There’s one feature of BERT which I think is a mistake and I’m writing to ask if you would consider changing it or if you would provide some way for it to be switched off.

I refer to the way that data returned by the R function being called is “truncated or padded with empty strings” before being presented in Excel. I think you will understand what I mean by this, for example Duncan Werner described the feature on 9 June at https://github.com/sdllc/Basic-Excel-R-Toolkit/issues/55 #

I understand why you chose to do this. Excel’s default behaviour for an array formula that returns data smaller than the range the array formula occupies is to display #N/A! in the “redundant” cells. Users, especially those not familiar with Excel array formulas, might regard that as ugly.

However, there are quite a few draw-backs to the behaviour. In the examples below each `Myfunction` is a trivial wrap to an R function. For example, `Mydiag` is an R function that wraps `diag`, and can be called from Excel via BERT as `R.Mydiag`

Here are the drawbacks as I see them:

1.  **"Reducing” formulas don’t work correctly.**
For example `=SUM(R.Mydiag(5))` returns 1 if entered into a single cell. The Excel equivalent of the R function `diag` is `MUNIT`, and `=SUM(MUNIT(5))` returns 5 when entered into a single cell – which seems like the correct answer surely?

2. **Combining two calls to BERT in a single array formula may not work correctly.**
For example, suppose I define `Mycbind` as a wrap to `cbind` like this:
`Mycbind <-function(x,y){cbind(x,y)}`
then as R code I can execute `Mycbind(Mycbind(1,2),3)` to return a three-element array but the equivalent function in Excel won’t work:
`=R.Mycbind(R.Mycbind(1,2),3)`
The array returned to Excel will never include the element 3.

3. **Evaluation of formulas in the formula bar does not work correctly.**
With native Excel formulas one can select all or part of the formula in the formula bar hit F9 and that part of the formula is replaced by its evaluation, and the evaluation can be to a “literal array” such as `{1,2;3,4}`. This can be useful for formula debugging. In my tests, such evaluation of `R.Myfunction` always returns a singleton and never an array.

4. **Auto-Right-Sizing of array formulas won’t work.**
I use an add-in that can “Right-size” array formulas – I think that various commercial Excel add-ins provide something similar – it’s very useful to be able to select an array formula, run the macro (via Ribbon or keyboard) and have the formula re-entered to occupy just the right number of cells for the data it returns. But such code is pretty much doomed by the “truncate or pad” feature of array formulas that call R via BERT.

I think “R via BERT” functions would be considerably more useful within Excel if they can be combined with both native Excel function (e.g. VLOOKUP, INDEX, MMULT) and with array functions from other Add-ins the user might have. “Truncate and Pad” gets in the way of such useful combining in return for a to-my-mind cosmetic benefit that could be achieved in other ways.

These are two suggested courses of action for you:

1)	**Abandon “Truncate and Pad”.**
a.	Advantage: “R + BERT” functions co-exist with native Excel functions and with functions from other libraries much better. For me this would be a big improvement!
b.	Disadvantage: It’s a non-backward compatible change and might break some of your users’ spreadsheets.
c.	Disadvantage: Users would see #N/A! values more than they currently do.

2)	**Make “Truncate and Pad” optional.**
I’m thinking this would be a “global” setting for all calls via BERT to R, and exposed to the user in the “Options” dialog under Add-ins > Basic Excel R Tool-kit > Configure.
a.	Advantage: “R+BERT” can co-exists better with native Excel functions and other add-in functions.
b.	Advantage: If the default setting was “TRUE” for a new install then that would be backwards compatible for existing users.
c.	Disadvantage: Additional settings on the options dialog are additional complexity.
d.	WIBNI: Could this setting be made from code – say by writing to the Registry at HKCU\Software\BERT\TruncateAndPad

I’d be interested to hear your thoughts.

Kind regards

Philip

**Comment by duncanwerner** [comment]
I suspect you are right about truncating, that's probably a mistake (although it has uses), and adds a lot of unnecessary internal complexity; but what is wrong with padding? What if we stop truncating but keep padding (I'm not committing to that, just thinking it through).

**Comment by PGS62** [comment]
Hi Duncan
Of the problems I listed, truncation causes 1, 3 and 4; padding causes 2. So my strong preference would be to get rid of both of the features (or allow both to be switched off). If I had to choose only one feature to eliminate it would be truncation because I can "wrap" calls to BERT in my own code to undo the effect of padding" but obviously it's not possible to undo the effect of truncation. If users really don't want to see #N/A! values then it's straightforward to provide them with a (VBA or C++) function that does the padding in a nested call. Something like `=NoNAs(R.Myfunction(...))`

Surely you've got to like eliminating "unnecessary complexity"!

Philip

**Comment by duncanwerner** [comment]
Not just complexity, it would speed up function calls as well.  And as for a wrapper function, the appropriate place to do that would probably be in R, you could just wrap the result of your function.

**Comment by duncanwerner** [comment]
Test build:
https://github.com/sdllc/Basic-Excel-R-Toolkit/releases/tag/1.62.1

**Comment by PGS62** [comment]
Wow, thanks. 
That test build seems to work very well. It fixes all four of the "draw-backs" I listed in my original post. Do you think you can put that into production or are you concerned about backwards compatibility issues?
FWIW I wouldn't think that the "padding" could be done in R since, unlike Excel Variants (XLOPERs etc), elements of R arrays must all be of the same type so we couldn't pad a numeric array with null strings.  
Philip

**Comment by duncanwerner** [comment]
You can use a matrix of lists.  Not an easy thing to work with in R but maps properly.  As regards the test build, I'm thinking about it.  I think it's the correct thing to do, but I do worry about breaking compatibility.  

Testing:

```
#
# pad result of a function for large excel array.
# note this will not work (atm) in the shell, VBA, or from the ribbon menu
#
pad.result <- function(rslt){

  # scalar
  if( length(rslt) == 1 ){ return(rslt); }

  # xlfCaller
  ref <- BERT$.Excel(89); 
  n.rows <- nrow(ref);
  n.cols <- ncol(ref);

  # not square, need to think about proper behavior
  if(is.null(nrow(rslt))){
    return(matrix(rslt, nrow=n.rows, ncol=n.cols));
  }

  # create matrix of lists, default empty string
  mat <- matrix(list(""), nrow=n.rows, ncol=n.cols);
  cat(paste(n.rows, "x", n.cols, "\n"));
  print(mat);

  # fill
  for( i in 1:(min(n.rows, nrow(rslt)))){
    for( j in 1:(min(n.cols, ncol(rslt)))){
      mat[i,j] <- list(rslt[i,j]);
    }
  }

  mat; # rslt;
}
```

**Comment by PGS62** [comment]
Hi Duncan

Nice trick to use a matrix of one-element lists.

Today I did some further tests on 1.62.1 and ran into a problem. It seems that returning a dataframe via BERT 1.62.1 can crash Excel.

`Sub ThisMayCrashExcel()`
`'Crashes Excel when using BERT 1.62.1 but not when using BERT 1.61`
`    Dim Result`
`    Result = Application.Run("BERT.Exec", "data.frame(1:10,LETTERS[1:10])")`
`End Sub`

I can work-around this problem for the time being and I'll let you know if I see any additional problems.

Philip

**Comment by duncanwerner** [comment]
Here's an update that fixes the frame issue:
https://github.com/sdllc/Basic-Excel-R-Toolkit/releases/tag/1.61.2

**Comment by PGS62** [comment]
Thanks Duncan - that seems to work well. i.e. the 4 issues in my original post are all addressed and the crash bug looks to be fixed too. You posted it as 1.61.2 but I think that should have read 1.62.2.
Philip

**Comment by PGS62** [comment]
Ah, I've just realised that you most recent release 1.63.0 incorporates the change I requested (I'd been using your "pre-release" 1.61.2 for a while). Many thanks for the changes.

**Comment by malcook** [comment]
@PGS62 - can you share what excel add-in performs this "Auto-Right-Sizing of array formulas" and whether it works well with BERT now?  I'm eager to try.  Thanks.
