### ISSUE TITLE
Issue with data matrix initialization

### ISSUE THREAD

**Issue by FrankAcito** [sdllc/Basic-Excel-R-Toolkit#85]
Hello,
I get the following error when using my function from the Excel Insert Function menu:
Error in terms.formula(formula, data = data) : 
  '.' in formula and no 'data' argument

The function still works and returns the correct results. I do not get this error when I type the function directly. (I tried several ways of initializing the matrix dataInput, but still get the same error.
Here is my function:
ARegress <- function(dataInput=0) { mydata <- as.data.frame(dataInput)
 y <- mydata[,1];
 x <- mydata[,c(-1)];
regress <- lm(y~.,data=x);
pred <- regress$fitted.values
return(pred);
}
 Thanks for any help! BERT is a terrific add-in.
Frank Acito

**Comment by duncanwerner** [comment]
Just ignore it.  If you use the Excel insert function box, it will call your function a bunch of times with missing or invalid parameters, causing those errors.  There's no way for us to disable this, but for most purposes it's not harmful.

If your function is very expensive, however, you might want to validate parameters and exit early if you see nulls or empty values.
