### ISSUE TITLE
sorting character strings

### ISSUE THREAD

**Issue by StatsMan53** [sdllc/Basic-Excel-R-Toolkit#97]
In R, the sort function adapts to the type of the input data, but as a BERT function, it seems to require numeric data.

Place the following function in the BERT\functions directory
   sortem <- function(x) sort(x)

Place character data in A1:A9 and numeric data in B1:B9.  Array enter =R.sortem(A1:A9) in D1:D9, then copy/paste that range into E1:E9.  Each cell of D1:D9 (trying to sort character data) will contain #NULL!, but E1:E9 will contain the sorted numeric data, indicating that the issue is with BERT, not with the entry of the formula in Excel.

Using newly downloaded/installed BERT v.1.64.0 in Office 365 ProPlus.

![image](https://user-images.githubusercontent.com/33853646/35805410-bae10530-0a49-11e8-8da6-ceae91c5b82d.png)

**Comment by duncanwerner** [comment]
It's because the data is in a list. Try using unlist, like
```
my.sort <- function(mat){ sort(unlist(mat)) }
```
There's probably an error reported to the console when you run your function. Note that if you try to sort a mix of numbers and strings, it will convert everything to strings and you will get lexical sorting of numbers. Supporting mixed types would require a little more work (via the `method` parameter).

**Comment by StatsMan53** [comment]
That works, thanks.  Could I have determined that for myself?  If so, how?

**Comment by duncanwerner** [comment]
That's an error in the sort function, which it will print out to the console. If you see results like this, usually checking the console is a good idea. If you're trying to figure it out, I would also suggest passing the variable directly into the global environment so you can look at it and try the function interactively. Add this to your function

```r
my.sort <- function(mat){
  # set in global env so we can look at it
  mat <<- mat

  # sort (this will break)
  sort(mat)
}
```

then after you calculate in Excel, you can try it interactively in the console:

```r

> mat
     [,1]
[1,] "one"
[2,] "two"
[3,] "three"
> sort(mat)
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) :
  'x' must be atomic
> sort(unlist(mat))
[1] "one"   "three" "two"
>
```
